require 'openssl'

# A stream cipher, unlike block ciphers, doesn't have the notion
# of a dedicated decryption function. Encryption and decryption
# simply require xoring with the key stream generated by the
# stream cipher.

data = "Applied Crypto.rb"

cipher = OpenSSL::Cipher.new("rc4")
cipher.encrypt
key = cipher.random_key

encrypted = cipher.update(data)

decipher = OpenSSL::Cipher.new("rc4")
decipher.encrypt # !!!
decipher.key = key

decrypted = decipher.update(encrypted)
puts decrypted
puts decrypted == data

